"""
This type stub file was generated by pyright.
"""

logger = ...
def iter_namespace(ns_pkg): # -> Iterator[ModuleInfo]:
    ...

def get_namespace_plugins(ns_pkg=...): # -> dict[str, ModuleType]:
    ...

def list_plugins(ns_pkg=...): # -> None:
    ...

def plugin_enabled(name, plugin_list=...): # -> bool:
    ...

def load_legacy_plugin(plugin, plugin_paths): # -> ModuleType:
    ...

def load_plugins(settings): # -> list[ModuleType]:
    ...

def get_plugin_name(plugin): # -> str:
    """
    Plugins can be passed as module objects, however this breaks caching as
    module objects cannot be pickled. To work around this, all plugins are
    stringified post-initialization.
    """
    ...
