"""
This type stub file was generated by pyright.
"""

from .server import Server, shell

"""
    livereload
    ~~~~~~~~~~

    A python version of livereload.

    :copyright: (c) 2013 by Hsiaoming Yang
    :license: BSD, see LICENSE for more details.
"""
__version__ = ...
__author__ = ...
__homepage__ = ...
__all__ = ('Server', 'shell')
