"""
This type stub file was generated by pyright.
"""

from tornado import web
from tornado.websocket import WebSocketHandler

"""
    livereload.handlers
    ~~~~~~~~~~~~~~~~~~~

    HTTP and WebSocket handlers for livereload.

    :copyright: (c) 2013 by Hsiaoming Yang
    :license: BSD, see LICENSE for more details.
"""
logger = ...
class LiveReloadHandler(WebSocketHandler):
    DEFAULT_RELOAD_TIME = ...
    waiters = ...
    watcher = ...
    live_css = ...
    _last_reload_time = ...
    def allow_draft76(self): # -> Literal[True]:
        ...

    def check_origin(self, origin): # -> Literal[True]:
        ...

    def on_close(self): # -> None:
        ...

    def send_message(self, message): # -> None:
        ...

    @classmethod
    def start_tasks(cls): # -> None:
        ...

    @classmethod
    def poll_tasks(cls): # -> None:
        ...

    @classmethod
    def reload_waiters(cls, path=...): # -> None:
        ...

    def on_message(self, message): # -> None:
        """Handshake with livereload.js

        1. client send 'hello'
        2. server reply 'hello'
        3. client send 'info'
        """
        ...



class MtimeStaticFileHandler(web.StaticFileHandler):
    _static_mtimes: typing.Dict = ...
    @classmethod
    def get_content_modified_time(cls, abspath): # -> datetime:
        """Returns the time that ``abspath`` was last modified.

        May be overridden in subclasses.  Should return a `~datetime.datetime`
        object or None.
        """
        ...

    @classmethod
    def get_content_version(cls, abspath): # -> str:
        """Returns a version string for the resource at the given path.

        This class method may be overridden by subclasses.  The
        default implementation is a hash of the file's contents.

        .. versionadded:: 3.1
        """
        ...



class LiveReloadJSHandler(web.RequestHandler):
    def get(self): # -> None:
        ...



class ForceReloadHandler(web.RequestHandler):
    def get(self): # -> None:
        ...



class StaticFileHandler(MtimeStaticFileHandler):
    def should_return_304(self): # -> Literal[False]:
        ...
