"""
This type stub file was generated by pyright.
"""

import sys
from tornado.wsgi import WSGIContainer
from tornado import web

"""
    livereload.server
    ~~~~~~~~~~~~~~~~~

    WSGI app server for livereload.

    :copyright: (c) 2013 - 2015 by Hsiaoming Yang
    :license: BSD, see LICENSE for more details.
"""
if sys.version_info >= (3, 8) and sys.platform == 'win32':
    ...
logger = ...
HEAD_END = ...
def set_header(fn, name, value): # -> Callable[..., None]:
    """Helper Function to Add HTTP headers to the server"""
    ...

def shell(cmd, output=..., mode=..., cwd=..., shell=...): # -> Callable[[], OSError | str | None]:
    """Execute a shell command.

    You can add a shell command::

        server.watch(
            'style.less', shell('lessc style.less', output='style.css')
        )

    :param cmd: a shell command, string or list
    :param output: output stdout to the given file
    :param mode: only works with output, mode ``w`` means write,
                 mode ``a`` means append
    :param cwd: set working directory before command is executed.
    :param shell: if true, on Unix the executable argument specifies a
                  replacement shell for the default ``/bin/sh``.
    """
    ...

class LiveScriptInjector(web.OutputTransform):
    def __init__(self, request) -> None:
        ...

    def transform_first_chunk(self, status_code, headers, chunk, finishing): # -> tuple[int, HTTPHeaders, bytes]:
        ...



class LiveScriptContainer(WSGIContainer):
    def __init__(self, wsgi_app, script=...) -> None:
        ...

    def __call__(self, request): # -> None:
        ...



class Server:
    """Livereload server interface.

    Initialize a server and watch file changes::

        server = Server(wsgi_app)
        server.serve()

    :param app: a WSGI application instance
    :param watcher: A Watcher instance, you don't have to initialize
                    it by yourself. Under Linux, you will want to install
                    pyinotify and use INotifyWatcher() to avoid wasted
                    CPU usage.
    """
    def __init__(self, app=..., watcher=...) -> None:
        ...

    def setHeader(self, name, value): # -> None:
        """Add or override HTTP headers at the at the beginning of the
           request.

        Once you have initialized a server, you can add one or more
        headers before starting the server::

            server.setHeader('Access-Control-Allow-Origin', '*')
            server.setHeader('Access-Control-Allow-Methods', '*')
            server.serve()

        :param name: The name of the header field to be defined.
        :param value: The value of the header field to be defined.
        """
        ...

    def watch(self, filepath, func=..., delay=..., ignore=...): # -> None:
        """Add the given filepath for watcher list.

        Once you have initialized a server, watch file changes before
        serve the server::

            server.watch('static/*.stylus', 'make static')
            def alert():
                print('foo')
            server.watch('foo.txt', alert)
            server.serve()

        :param filepath: files to be watched, it can be a filepath,
                         a directory, or a glob pattern
        :param func: the function to be called, it can be a string of
                     shell command, or any callable object without
                     parameters
        :param delay: Delay sending the reload message. Use 'forever' to
                      not send it. This is useful to compile sass files to
                      css, but reload on changed css files then only.
        :param ignore: A function return True to ignore a certain pattern of
                       filepath.
        """
        ...

    def application(self, port, host, liveport=..., debug=..., live_css=...): # -> None:
        class ConfiguredTransform(LiveScriptInjector):
            ...



    def get_web_handlers(self, script): # -> list[tuple[str, type[FallbackHandler], dict[str, LiveScriptContainer]]] | list[tuple[str, type[StaticFileHandler], dict[str, Any]]]:
        ...

    def serve(self, port=..., liveport=..., host=..., root=..., debug=..., open_url=..., restart_delay=..., open_url_delay=..., live_css=..., default_filename=...): # -> None:
        """Start serve the server with the given port.

        :param port: serve on this port, default is 5500
        :param liveport: live reload on this port
        :param host: serve on this hostname, default is 127.0.0.1
        :param root: serve static on this root directory
        :param debug: set debug mode, which autoreloads the app on code changes
                      via Tornado (and causes polling). Defaults to True when
                      ``self.app`` is set, otherwise False.
        :param open_url_delay: open webbrowser after the delay seconds
        :param live_css: whether to use live css or force reload on css.
                         Defaults to True
        :param default_filename: launch this file from the selected root on startup
        """
        ...
