"""
This type stub file was generated by pyright.
"""

"""
    livereload.watcher
    ~~~~~~~~~~~~~~~~~~

    A file watch management for LiveReload Server.

    :copyright: (c) 2013 - 2015 by Hsiaoming Yang
    :license: BSD, see LICENSE for more details.
"""
logger = ...
class Watcher:
    """A file watcher registry."""
    def __init__(self) -> None:
        ...

    def ignore_dirs(self, *args): # -> None:
        ...

    def remove_dirs_from_ignore(self, *args): # -> None:
        ...

    def ignore(self, filename): # -> bool:
        """Ignore a given filename or not."""
        ...

    def watch(self, path, func=..., delay=..., ignore=...): # -> None:
        """Add a task to watcher.

        :param path: a filepath or directory path or glob pattern
        :param func: the function to be executed when file changed
        :param delay: Delay sending the reload message. Use 'forever' to
                      not send it. This is useful to compile sass files to
                      css, but reload on changed css files then only.
        :param ignore: A function return True to ignore a certain pattern of
                       filepath.
        """
        ...

    def start(self, callback): # -> Literal[False]:
        """Start the watcher running, calling callback when changes are
        observed. If this returns False, regular polling will be used."""
        ...

    def examine(self): # -> tuple[None, Any | None]:
        """Check if there are changes. If so, run the given task.

        Returns a tuple of modified filepath and reload delay.
        """
        ...

    def is_changed(self, path, ignore=...): # -> bool | list[Any]:
        """Check if any filepaths have been added, modified, or removed.

        Updates filepath modification times in self._task_mtimes.
        """
        ...

    def is_file_removed(self): # -> bool:
        """Check if any filepaths have been removed since last check.

        Deletes removed paths from self._task_mtimes.
        Sets self.filepath to one of the removed paths.
        """
        ...

    def is_file_changed(self, path, ignore=...): # -> bool:
        """Check if filepath has been added or modified since last check.

        Updates filepath modification times in self._new_mtimes.
        Sets self.filepath to changed path.
        """
        ...

    def is_folder_changed(self, path, ignore=...): # -> bool:
        """Check if directory path has any changed filepaths."""
        ...

    def get_changed_glob_files(self, path, ignore=...): # -> list[Any]:
        """Check if glob path has any changed filepaths."""
        ...



class INotifyWatcher(Watcher):
    def __init__(self) -> None:
        ...

    def watch(self, path, func=..., delay=..., ignore=...): # -> None:
        ...

    def inotify_event(self, event): # -> None:
        ...

    def start(self, callback): # -> Literal[True]:
        ...



def get_watcher_class(): # -> type[Watcher] | type[INotifyWatcher]:
    ...
