"""
This type stub file was generated by pyright.
"""

import argparse
import importlib.metadata
import json
import logging
import multiprocessing
import os
import pprint
import sys
import time
import traceback
from collections.abc import Iterable
from pkgutil import extend_path
from pelican.log import DEFAULT_LOG_HANDLER, console, init as init_logging
from pelican.generators import ArticlesGenerator, PagesGenerator, SourceFileGenerator, StaticGenerator, TemplatePagesGenerator
from pelican.plugins import signals
from pelican.plugins._utils import get_plugin_name, load_plugins
from pelican.server import ComplexHTTPRequestHandler, RootedHTTPServer
from pelican.settings import read_settings
from pelican.utils import clean_output_dir, maybe_pluralize, wait_for_changes
from pelican.writers import Writer

__path__ = ...
__version__ = ...
DEFAULT_CONFIG_NAME = ...
logger = ...
class Pelican:
    def __init__(self, settings) -> None:
        """Pelican initialization

        Performs some checks on the environment before doing anything else.
        """
        ...

    def init_path(self): # -> None:
        ...

    def init_plugins(self): # -> None:
        ...

    def run(self): # -> None:
        """Run the generators and return"""
        ...



class PrintSettings(argparse.Action):
    def __call__(self, parser, namespace, values, option_string):
        ...



class ParseOverrides(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=...): # -> None:
        ...



LOG_HANDLERS = ...
def parse_arguments(argv=...): # -> Namespace:
    ...

def get_config(args): # -> dict[Any, Any]:
    """Builds a config dictionary based on supplied `args`."""
    ...

def get_instance(args): # -> tuple[Any, Settings]:
    ...

def autoreload(args, excqueue=...): # -> None:
    ...

def listen(server, port, output, excqueue=...): # -> None:
    ...

def main(argv=...): # -> None:
    ...
