"""
This type stub file was generated by pyright.
"""

logger = ...
class FileDataCacher:
    """Class that can cache data contained in files"""
    def __init__(self, settings, cache_name, caching_policy, load_policy) -> None:
        """Load the specified cache within CACHE_PATH in settings

        only if *load_policy* is True,
        May use gzip if GZIP_CACHE ins settings is True.
        Sets caching policy according to *caching_policy*.
        """
        ...

    def cache_data(self, filename, data): # -> None:
        """Cache data for given file"""
        ...

    def get_cached_data(self, filename, default=...): # -> Any | None:
        """Get cached data for the given file

        if no data is cached, return the default object
        """
        ...

    def save_cache(self): # -> None:
        """Save the updated cache"""
        ...



class FileStampDataCacher(FileDataCacher):
    """Subclass that also caches the stamp of the file"""
    def __init__(self, settings, cache_name, caching_policy, load_policy) -> None:
        """This subclass additionally sets filestamp function
        and base path for filestamping operations
        """
        ...

    def cache_data(self, filename, data): # -> None:
        """Cache stamp and data for the given file"""
        ...

    def get_cached_data(self, filename, default=...): # -> Any | None:
        """Get the cached data for the given filename
        if the file has not been modified.

        If no record exists or file has been modified, return default.
        Modification is checked by comparing the cached
        and current file stamp.
        """
        ...
