"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from pelican.settings import Settings
from pelican.utils import deprecated_attribute, memoized

logger = ...
class Content:
    """Represents a content.

    :param content: the string to parse, containing the original content.
    :param metadata: the metadata associated to this page (optional).
    :param settings: the settings dictionary (optional).
    :param source_path: The location of the source of this content (if any).
    :param context: The shared context between generators.

    """
    default_template: Optional[str] = ...
    mandatory_properties: tuple[str, ...] = ...
    @deprecated_attribute(old="filename", new="source_path", since=(3, 2, 0))
    def filename(): # -> None:
        ...

    def __init__(self, content: str, metadata: Optional[dict[str, Any]] = ..., settings: Optional[Settings] = ..., source_path: Optional[str] = ..., context: Optional[dict[Any, Any]] = ...) -> None:
        ...

    def __str__(self) -> str:
        ...

    def is_valid(self) -> bool:
        """Validate Content"""
        ...

    @property
    def url_format(self) -> dict[str, Any]:
        """Returns the URL, formatted with the proper values"""
        ...

    def get_url_setting(self, key: str) -> str:
        ...

    def get_static_links(self) -> set[str]:
        ...

    def get_siteurl(self) -> str:
        ...

    @memoized
    def get_content(self, siteurl: str) -> str:
        ...

    @property
    def content(self) -> str:
        ...

    @memoized
    def get_summary(self, siteurl: str) -> str:
        """Returns the summary of an article.

        This is based on the summary metadata if set, otherwise truncate the
        content.
        """
        ...

    @property
    def summary(self) -> str:
        ...

    @summary.setter
    def summary(self, value: str): # -> None:
        """Dummy function"""
        ...

    @property
    def status(self) -> str:
        ...

    @status.setter
    def status(self, value: str) -> None:
        ...

    @property
    def url(self) -> str:
        ...

    @property
    def save_as(self) -> str:
        ...

    def get_relative_source_path(self, source_path: Optional[str] = ...) -> Optional[str]:
        """Return the relative path (from the content path) to the given
        source_path.

        If no source path is specified, use the source path of this
        content object.
        """
        ...

    @property
    def relative_dir(self) -> str:
        ...

    def refresh_metadata_intersite_links(self) -> None:
        ...



class SkipStub(Content):
    """Stub class representing content that should not be processed in any way."""
    def __init__(self, content, metadata=..., settings=..., source_path=..., context=...) -> None:
        ...

    def is_valid(self): # -> Literal[False]:
        ...

    @property
    def content(self):
        ...

    @property
    def save_as(self):
        ...



class Page(Content):
    mandatory_properties = ...
    allowed_statuses = ...
    default_status = ...
    default_template = ...


class Article(Content):
    mandatory_properties = ...
    allowed_statuses = ...
    default_status = ...
    default_template = ...
    def __init__(self, *args, **kwargs) -> None:
        ...



class Static(Content):
    mandatory_properties = ...
    default_status = ...
    default_template = ...
    def __init__(self, *args, **kwargs) -> None:
        ...

    @deprecated_attribute(old="filepath", new="source_path", since=(3, 2, 0))
    def filepath(): # -> None:
        ...

    @deprecated_attribute(old="src", new="source_path", since=(3, 2, 0))
    def src(): # -> None:
        ...

    @deprecated_attribute(old="dst", new="save_as", since=(3, 2, 0))
    def dst(): # -> None:
        ...

    @property
    def url(self) -> str:
        ...

    @property
    def save_as(self) -> str:
        ...

    def attach_to(self, content: Content) -> None:
        """Override our output directory with that of the given content object."""
        ...
