"""
This type stub file was generated by pyright.
"""

from typing import Optional
from jinja2 import BaseLoader
from pelican.cache import FileStampDataCacher

logger = ...
class PelicanTemplateNotFound(Exception):
    ...


class Generator:
    """Baseclass generator"""
    def __init__(self, context, settings, path, theme, output_path, readers_cache_name=..., **kwargs) -> None:
        ...

    def get_template(self, name):
        """Return the template by name.
        Use self.theme to get the templates to use, and return a list of
        templates ready to use with Jinja2.
        """
        ...

    def get_files(self, paths, exclude: Optional[list[str]] = ..., extensions=...) -> set[str]:
        """Return a list of files to use, based on rules

        :param paths: the list pf paths to search (relative to self.path)
        :param exclude: the list of path to exclude
        :param extensions: the list of allowed extensions (if False, all
            extensions are allowed)
        """
        ...

    def add_source_path(self, content, static=...): # -> None:
        """Record a source file path that a Generator found and processed.
        Store a reference to its Content object, for url lookups later.
        """
        ...

    def add_static_links(self, content): # -> None:
        """Add file links in content to context to be processed as Static
        content.
        """
        ...

    def __str__(self) -> str:
        ...



class CachingGenerator(Generator, FileStampDataCacher):
    """Subclass of Generator and FileStampDataCacher classes

    enables content caching, either at the generator or reader level
    """
    def __init__(self, *args, **kwargs) -> None:
        """Initialize the generator, then set up caching

        note the multiple inheritance structure
        """
        ...



class _FileLoader(BaseLoader):
    def __init__(self, path, basedir) -> None:
        ...

    def get_source(self, environment, template): # -> tuple[str, str, Callable[[], bool]]:
        ...



class TemplatePagesGenerator(Generator):
    def generate_output(self, writer): # -> None:
        ...



class ArticlesGenerator(CachingGenerator):
    """Generate blog articles"""
    def __init__(self, *args, **kwargs) -> None:
        """initialize properties"""
        ...

    def generate_feeds(self, writer): # -> None:
        """Generate the feeds from the current context, and output files."""
        ...

    def generate_articles(self, write): # -> None:
        """Generate the articles."""
        ...

    def generate_period_archives(self, write): # -> None:
        """Generate per-year, per-month, and per-day archives."""
        ...

    def generate_direct_templates(self, write): # -> None:
        """Generate direct templates pages"""
        ...

    def generate_tags(self, write): # -> None:
        """Generate Tags pages."""
        ...

    def generate_categories(self, write): # -> None:
        """Generate category pages."""
        ...

    def generate_authors(self, write): # -> None:
        """Generate Author pages."""
        ...

    def generate_drafts(self, write): # -> None:
        """Generate drafts pages."""
        ...

    def generate_pages(self, writer): # -> None:
        """Generate the pages on the disk"""
        ...

    def check_disabled_readers(self) -> None:
        ...

    def generate_context(self): # -> None:
        """Add the articles into the shared context"""
        ...

    def generate_output(self, writer): # -> None:
        ...

    def refresh_metadata_intersite_links(self): # -> None:
        ...



class PagesGenerator(CachingGenerator):
    """Generate pages"""
    def __init__(self, *args, **kwargs) -> None:
        ...

    def check_disabled_readers(self) -> None:
        ...

    def generate_context(self): # -> None:
        ...

    def generate_output(self, writer): # -> None:
        ...

    def refresh_metadata_intersite_links(self): # -> None:
        ...



class StaticGenerator(Generator):
    """copy static paths (what you want to copy, like images, medias etc.
    to output"""
    def __init__(self, *args, **kwargs) -> None:
        ...

    def check_disabled_readers(self) -> None:
        ...

    def generate_context(self): # -> None:
        ...

    def generate_output(self, writer): # -> None:
        ...



class SourceFileGenerator(Generator):
    def generate_context(self): # -> None:
        ...

    def generate_output(self, writer=...): # -> None:
        ...
