"""
This type stub file was generated by pyright.
"""

import logging

__all__ = ["init"]
console = ...
class LimitFilter(logging.Filter):
    """
    Remove duplicates records, and limit the number of records in the same
    group.

    Groups are specified by the message to use when the number of records in
    the same group hit the limit.
    E.g.: log.warning(('43 is not the answer', 'More erroneous answers'))
    """
    LOGS_DEDUP_MIN_LEVEL = ...
    _ignore = ...
    _raised_messages = ...
    _threshold = ...
    _group_count = ...
    def filter(self, record): # -> bool:
        ...



class LimitLogger(logging.Logger):
    """
    A logger which adds LimitFilter automatically
    """
    limit_filter = ...
    def __init__(self, *args, **kwargs) -> None:
        ...

    def disable_filter(self): # -> None:
        ...

    def enable_filter(self): # -> None:
        ...



class FatalLogger(LimitLogger):
    warnings_fatal = ...
    errors_fatal = ...
    def warning(self, *args, stacklevel=..., **kwargs): # -> None:
        """
        Displays a logging warning.

        Wrapping it here allows Pelican to filter warnings, and conditionally
        make warnings fatal.

        Args:
            stacklevel (int): the stacklevel that would be used to display the
            calling location, except for this function. Adjusting the
            stacklevel allows you to see the "true" calling location of the
            warning, rather than this wrapper location.
        """
        ...

    def error(self, *args, stacklevel=..., **kwargs): # -> None:
        """
        Displays a logging error.

        Wrapping it here allows Pelican to filter errors, and conditionally
        make errors non-fatal.

        Args:
            stacklevel (int): the stacklevel that would be used to display the
            calling location, except for this function. Adjusting the
            stacklevel allows you to see the "true" calling location of the
            error, rather than this wrapper location.
        """
        ...



DEFAULT_LOG_HANDLER = ...
def init(level=..., fatal=..., handler=..., name=..., logs_dedup_min_level=...): # -> None:
    ...

def log_warnings(): # -> None:
    ...

if __name__ == "__main__":
    root_logger = ...
