"""
This type stub file was generated by pyright.
"""

from html.parser import HTMLParser
from docutils.writers.html4css1 import HTMLTranslator, Writer
from pelican.cache import FileStampDataCacher

_DISCARD = ...
DUPLICATES_DEFINITIONS_ALLOWED = ...
METADATA_PROCESSORS = ...
logger = ...
def ensure_metadata_list(text): # -> list[str | Any]:
    """Canonicalize the format of a list of authors or tags.  This works
    the same way as Docutils' "authors" field: if it's already a list,
    those boundaries are preserved; otherwise, it must be a string;
    if the string contains semicolons, it is split on semicolons;
    otherwise, it is split on commas.  This allows you to write
    author lists in either "Jane Doe, John Doe" or "Doe, Jane; Doe, John"
    format.

    Regardless, all list items undergo .strip() before returning, and
    empty items are discarded.
    """
    ...

class BaseReader:
    """Base class to read files.

    This class is used to process static files, and it can be inherited for
    other types of file. A Reader class must have the following attributes:

    - enabled: (boolean) tell if the Reader class is enabled. It
      generally depends on the import of some dependency.
    - file_extensions: a list of file extensions that the Reader will process.
    - extensions: a list of extensions to use in the reader (typical use is
      Markdown).

    """
    enabled = ...
    file_extensions = ...
    extensions = ...
    def __init__(self, settings) -> None:
        ...

    def process_metadata(self, name, value):
        ...

    def read(self, source_path): # -> tuple[None, dict[Any, Any]]:
        "No-op parser"
        ...

    def disabled_message(self) -> str:
        """Message about why this plugin was disabled."""
        ...



class _FieldBodyTranslator(HTMLTranslator):
    def __init__(self, document) -> None:
        ...

    def astext(self): # -> str:
        ...

    def visit_field_body(self, node): # -> None:
        ...

    def depart_field_body(self, node): # -> None:
        ...



def render_node_to_html(document, node, field_body_translator_class):
    ...

class PelicanHTMLWriter(Writer):
    def __init__(self) -> None:
        ...



class PelicanHTMLTranslator(HTMLTranslator):
    def visit_abbreviation(self, node): # -> None:
        ...

    def depart_abbreviation(self, node): # -> None:
        ...

    def visit_image(self, node): # -> None:
        ...



class RstReader(BaseReader):
    """Reader for reStructuredText files

    By default the output HTML is written using
    docutils.writers.html4css1.Writer and translated using a subclass of
    docutils.writers.html4css1.HTMLTranslator. If you want to override it with
    your own writer/translator (e.g. a HTML5-based one), pass your classes to
    these two attributes. Look in the source code for details.

        writer_class                    Used for writing contents
        field_body_translator_class     Used for translating metadata such
            as article summary

    """
    enabled = ...
    file_extensions = ...
    writer_class = PelicanHTMLWriter
    field_body_translator_class = _FieldBodyTranslator
    def __init__(self, *args, **kwargs) -> None:
        ...

    def read(self, source_path): # -> tuple[str | None, dict[Any, Any]]:
        """Parses restructured text"""
        ...



class MarkdownReader(BaseReader):
    """Reader for Markdown files"""
    enabled = ...
    file_extensions = ...
    def __init__(self, *args, **kwargs) -> None:
        ...

    def read(self, source_path): # -> tuple[str | Any, dict[Any, Any]]:
        """Parse content and metadata of markdown files"""
        ...

    def disabled_message(self) -> str:
        ...



class HTMLReader(BaseReader):
    """Parses HTML files as input, looking for meta, title, and body tags"""
    file_extensions = ...
    enabled = ...
    class _HTMLParser(HTMLParser):
        def __init__(self, settings, filename) -> None:
            ...

        def handle_starttag(self, tag, attrs): # -> None:
            ...

        def handle_endtag(self, tag): # -> None:
            ...

        def handle_startendtag(self, tag, attrs): # -> None:
            ...

        def handle_comment(self, data): # -> None:
            ...

        def handle_data(self, data): # -> None:
            ...

        def handle_entityref(self, data): # -> None:
            ...

        def handle_charref(self, data): # -> None:
            ...

        def build_tag(self, tag, attrs, close_tag): # -> str:
            ...



    def read(self, filename): # -> tuple[str | Any, dict[Any, Any]]:
        """Parse content and metadata of HTML files"""
        ...



class Readers(FileStampDataCacher):
    """Interface for all readers.

    This class contains a mapping of file extensions / Reader classes, to know
    which Reader class must be used to read a file (based on its extension).
    This is customizable both with the 'READERS' setting, and with the
    'readers_init' signall for plugins.

    """
    def __init__(self, settings=..., cache_name=...) -> None:
        ...

    @property
    def extensions(self): # -> dict_keys[Any, Any]:
        """File extensions that will be processed by a reader."""
        ...

    @property
    def disabled_extensions(self): # -> dict_keys[Any, Any]:
        ...

    def read_file(self, base_path, path, content_class=..., fmt=..., context=..., preread_signal=..., preread_sender=..., context_signal=..., context_sender=...): # -> Page | SkipStub:
        """Return a content object parsed with the given format."""
        ...

    def check_file(self, source_path: str) -> None:
        """Log a warning if a file is processed by a disabled reader."""
        ...



def find_empty_alt(content, path): # -> None:
    """Find images with empty alt

    Create warnings for all images with empty alt (up to a certain number),
    as they are really likely to be accessibility flaws.

    """
    ...

def default_metadata(settings=..., process=...): # -> dict[Any, Any]:
    ...

def path_metadata(full_path, source_path, settings=...): # -> dict[Any, Any]:
    ...

def parse_path_metadata(source_path, settings=..., process=...): # -> dict[Any, Any]:
    r"""Extract a metadata dictionary from a file's path

    >>> import pprint
    >>> settings = {
    ...     'FILENAME_METADATA': r'(?P<slug>[^.]*).*',
    ...     'PATH_METADATA':
    ...         r'(?P<category>[^/]*)/(?P<date>\d{4}-\d{2}-\d{2})/.*',
    ...     }
    >>> reader = BaseReader(settings=settings)
    >>> metadata = parse_path_metadata(
    ...     source_path='my-cat/2013-01-01/my-slug.html',
    ...     settings=settings,
    ...     process=reader.process_metadata)
    >>> pprint.pprint(metadata)  # doctest: +ELLIPSIS
    {'category': <pelican.urlwrappers.Category object at ...>,
     'date': datetime.datetime(2013, 1, 1, 0, 0),
     'slug': 'my-slug'}
    """
    ...
