"""
This type stub file was generated by pyright.
"""

from http import server

logger = ...
def parse_arguments(): # -> Namespace:
    ...

class ComplexHTTPRequestHandler(server.SimpleHTTPRequestHandler):
    SUFFIXES = ...
    extensions_map = ...
    def translate_path(self, path):
        ...

    def do_GET(self): # -> None:
        ...

    def get_path_that_exists(self, original_path): # -> None:
        ...

    def guess_type(self, path): # -> str:
        """Guess at the mime type for the specified file."""
        ...

    def log_message(self, format, *args): # -> None:
        ...



class RootedHTTPServer(server.HTTPServer):
    def __init__(self, base_path, *args, **kwargs) -> None:
        ...



if __name__ == "__main__":
    args = ...
    httpd = ...
