"""
This type stub file was generated by pyright.
"""

from types import ModuleType
from typing import Any, Optional

def load_source(name: str, path: str) -> ModuleType:
    ...

logger = ...
Settings = dict[str, Any]
DEFAULT_THEME = ...
DEFAULT_CONFIG = ...
PYGMENTS_RST_OPTIONS = ...
def read_settings(path: Optional[str] = ..., override: Optional[Settings] = ...) -> Settings:
    ...

def get_settings_from_module(module: Optional[ModuleType] = ...) -> Settings:
    """Loads settings from a module, returns a dictionary."""
    ...

def get_settings_from_file(path: str) -> Settings:
    """Loads settings from a file path, returning a dict."""
    ...

def get_jinja_environment(settings: Settings) -> Settings:
    """Sets the environment for Jinja"""
    ...

def handle_deprecated_settings(settings: Settings) -> Settings:
    """Converts deprecated settings and issues warnings. Issues an exception
    if both old and new setting is specified.
    """
    ...

def configure_settings(settings: Settings) -> Settings:
    """Provide optimizations, error checking, and warnings for the given
    settings.
    Also, specify the log messages to be ignored.
    """
    ...
