"""
This type stub file was generated by pyright.
"""

import functools

logger = ...
@functools.total_ordering
class URLWrapper:
    def __init__(self, name, settings) -> None:
        ...

    @property
    def name(self): # -> Any:
        ...

    @name.setter
    def name(self, name): # -> None:
        ...

    @property
    def slug(self): # -> str:
        ...

    @slug.setter
    def slug(self, slug): # -> None:
        ...

    def as_dict(self): # -> dict[str, Any]:
        ...

    def __hash__(self) -> int:
        ...

    def __eq__(self, other) -> bool:
        ...

    def __ne__(self, other) -> bool:
        ...

    def __lt__(self, other) -> bool:
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self): # -> str:
        ...

    page_name = ...
    url = ...
    save_as = ...


class Category(URLWrapper):
    ...


class Tag(URLWrapper):
    def __init__(self, name, *args, **kwargs) -> None:
        ...



class Author(URLWrapper):
    ...
