"""
This type stub file was generated by pyright.
"""

import datetime
import pathlib
import watchfiles
from collections.abc import Collection, Generator, Iterable, Sequence
from contextlib import contextmanager
from html.parser import HTMLParser
from typing import Any, Callable, TYPE_CHECKING
from watchfiles import Change
from pelican.contents import Content
from pelican.settings import Settings

if TYPE_CHECKING:
    ...
logger = ...
def sanitised_join(base_directory: str, *parts: str) -> str:
    ...

def strftime(date: datetime.datetime, date_format: str) -> str:
    """
    Enhanced replacement for built-in strftime with zero stripping

    This works by 'grabbing' possible format strings (those starting with %),
    formatting them with the date, stripping any leading zeros if - prefix is
    used and replacing formatted output back.
    """
    ...

class SafeDatetime(datetime.datetime):
    """Subclass of datetime that works with utf-8 format strings on PY2"""
    def strftime(self, fmt, safe=...): # -> str:
        """Uses our custom strftime if supposed to be *safe*"""
        ...



class DateFormatter:
    """A date formatter object used as a jinja filter

    Uses the `strftime` implementation and makes sure jinja uses the locale
    defined in LOCALE setting
    """
    def __init__(self) -> None:
        ...

    def __call__(self, date: datetime.datetime, date_format: str) -> str:
        ...



class memoized:
    """Function decorator to cache return values.

    If called later with the same arguments, the cached value is returned
    (not reevaluated).

    """
    def __init__(self, func: Callable) -> None:
        ...

    def __call__(self, *args) -> Any:
        ...

    def __repr__(self) -> str | None:
        ...

    def __get__(self, obj: Any, objtype): # -> partial[Any]:
        """Support instance methods."""
        ...



def deprecated_attribute(old: str, new: str, since: tuple[int, ...], remove: tuple[int, ...] | None = ..., doc: str | None = ...): # -> Callable[..., property]:
    """Attribute deprecation decorator for gentle upgrades

    For example:

        class MyClass (object):
            @deprecated_attribute(
                old='abc', new='xyz', since=(3, 2, 0), remove=(4, 1, 3))
            def abc(): return None

            def __init__(self):
                xyz = 5

    Note that the decorator needs a dummy method to attach to, but the
    content of the dummy method is ignored.
    """
    ...

def get_date(string: str) -> datetime.datetime:
    """Return a datetime object from a string.

    If no format matches the given date, raise a ValueError.
    """
    ...

@contextmanager
def pelican_open(filename: str, mode: str = ..., strip_crs: bool = ...) -> Generator[str, None, None]:
    """Open a file and return its content"""
    ...

def slugify(value: str, regex_subs: Iterable[tuple[str, str]] = ..., preserve_case: bool = ..., use_unicode: bool = ...) -> str:
    """
    Normalizes string, converts to lowercase, removes non-alpha characters,
    and converts spaces to hyphens.

    Took from Django sources.

    For a set of sensible default regex substitutions to pass to regex_subs
    look into pelican.settings.DEFAULT_CONFIG['SLUG_REGEX_SUBSTITUTIONS'].
    """
    ...

def copy(source: str, destination: str, ignores: Iterable[str] | None = ...) -> None:
    """Recursively copy source into destination.

    If source is a file, destination has to be a file as well.
    The function is able to copy either files or directories.

    :param source: the source file or directory
    :param destination: the destination file or directory
    :param ignores: either None, or a list of glob patterns;
        files matching those patterns will _not_ be copied.
    """
    ...

def copy_file(source: str, destination: str) -> None:
    """Copy a file"""
    ...

def clean_output_dir(path: str, retention: Iterable[str]) -> None:
    """Remove all files from output directory except those in retention list"""
    ...

def get_relative_path(path: str) -> str:
    """Return the relative path from the given path to the root path."""
    ...

def path_to_url(path: str) -> str:
    """Return the URL corresponding to a given path."""
    ...

def posixize_path(rel_path: str) -> str:
    """Use '/' as path separator, so that source references,
    like '{static}/foo/bar.jpg' or 'extras/favicon.ico',
    will work on Windows as well as on Mac and Linux."""
    ...

class _HTMLWordTruncator(HTMLParser):
    _word_regex = ...
    _word_prefix_regex = ...
    _singlets = ...
    class TruncationCompleted(Exception):
        def __init__(self, truncate_at: int) -> None:
            ...



    def __init__(self, max_words: int) -> None:
        ...

    def feed(self, *args, **kwargs) -> None:
        ...

    def getoffset(self) -> int:
        ...

    def add_word(self, word_end: int) -> None:
        ...

    def add_last_word(self) -> None:
        ...

    def handle_starttag(self, tag: str, attrs: Any) -> None:
        ...

    def handle_endtag(self, tag: str) -> None:
        ...

    def handle_data(self, data: str) -> None:
        ...

    def handle_entityref(self, name: str) -> None:
        """
        Called when an entity ref like '&mdash;' is found

        `name` is the entity ref without ampersand and semicolon (e.g. `mdash`)
        """
        ...

    def handle_charref(self, name: str) -> None:
        """
        Called when a char ref like '&#8212;' or '&#x2014' is found

        `name` is the char ref without ampersand and semicolon (e.g. `#8212` or
        `#x2014`)
        """
        ...



def truncate_html_words(s: str, num: int, end_text: str = ...) -> str:
    """Truncates HTML to a certain number of words.

    (not counting tags and comments). Closes opened tags if they were correctly
    closed in the given html. Takes an optional argument of what should be used
    to notify that the string has been truncated, defaulting to ellipsis (…).

    Newlines in the HTML are preserved. (From the django framework).
    """
    ...

def truncate_html_paragraphs(s, count): # -> LiteralString:
    """Truncate HTML to a certain number of paragraphs.

    :param count: number of paragraphs to keep

    Newlines in the HTML are preserved.
    """
    ...

def process_translations(content_list: list[Content], translation_id: str | Collection[str] | None = ...) -> tuple[list[Content], list[Content]]:
    """Finds translations and returns them.

    For each content_list item, populates the 'translations' attribute, and
    returns a tuple with two lists (index, translations). Index list includes
    items in default language or items which have no variant in default
    language. Items with the `translation` metadata set to something else than
    `False` or `false` will be used as translations, unless all the items in
    the same group have that metadata.

    Translations and original items are determined relative to one another
    amongst items in the same group. Items are in the same group if they
    have the same value(s) for the metadata attribute(s) specified by the
    'translation_id', which must be a string or a collection of strings.
    If 'translation_id' is falsy, the identification of translations is skipped
    and all items are returned as originals.
    """
    ...

def get_original_items(items: list[Content], with_str: str) -> list[Content]:
    ...

def order_content(content_list: list[Content], order_by: str | Callable[[Content], Any] | None = ...) -> list[Content]:
    """Sorts content.

    order_by can be a string of an attribute or sorting function. If order_by
    is defined, content will be ordered by that attribute or sorting function.
    By default, content is ordered by slug.

    Different content types can have default order_by attributes defined
    in settings, e.g. PAGES_ORDER_BY='sort-order', in which case `sort-order`
    should be a defined metadata attribute in each page.
    """
    ...

class FileChangeFilter(watchfiles.DefaultFilter):
    def __init__(self, ignore_file_patterns: Sequence[str], *args, **kwargs) -> None:
        ...

    def __call__(self, change: watchfiles.Change, path: str) -> bool:
        """Returns `True` if a file should be watched for changes. The `IGNORE_FILES`
        setting is a list of Unix glob patterns. This call will filter out files and
        directories specified by `IGNORE_FILES` Pelican setting and by the default
        filters of `watchfiles.DefaultFilter`, seen here:
        https://watchfiles.helpmanual.io/api/filters/#watchfiles.DefaultFilter.ignore_dirs
        """
        ...



def wait_for_changes(settings_file: str, settings: Settings) -> set[tuple[Change, str]]:
    ...

def set_date_tzinfo(d: datetime.datetime, tz_name: str | None = ...) -> datetime.datetime:
    """Set the timezone for dates that don't have tzinfo"""
    ...

def mkdir_p(path: str) -> None:
    ...

def split_all(path: str | pathlib.Path | None) -> Sequence[str] | None:
    """Split a path into a list of components

    While os.path.split() splits a single component off the back of
    `path`, this function splits all components:

    >>> split_all(os.path.join('a', 'b', 'c'))
    ['a', 'b', 'c']
    """
    ...

def path_to_file_url(path: str) -> str:
    """Convert file-system path to file:// URL"""
    ...

def maybe_pluralize(count: int, singular: str, plural: str) -> str:
    """
    Returns a formatted string containing count and plural if count is not 1
    Returns count and singular if count is 1

    maybe_pluralize(0, 'Article', 'Articles') -> '0 Articles'
    maybe_pluralize(1, 'Article', 'Articles') -> '1 Article'
    maybe_pluralize(2, 'Article', 'Articles') -> '2 Articles'

    """
    ...

@contextmanager
def temporary_locale(temp_locale: str | None = ..., lc_category: int = ...) -> Generator[None, None, None]:
    """
    Enable code to run in a context with a temporary locale
    Resets the locale back when exiting context.

    Use tests.support.TestCaseWithCLocale if you want every unit test in a
    class to use the C locale.
    """
    ...

def file_suffix(path: str) -> str:
    """Return the suffix of a filename in a path."""
    ...
