"""
This type stub file was generated by pyright.
"""

logger = ...

class Writer:
    def __init__(self, output_path, settings=...) -> None: ...
    def write_feed(
        self,
        elements,
        context,
        path=...,
        url=...,
        feed_type=...,
        override_output=...,
        feed_title=...,
    ):  # -> Atom1Feed | Rss201rev2Feed:
        """Generate a feed with the list of articles provided

        Return the feed. If no path or output_path is specified, just
        return the feed object.

        :param elements: the articles to put on the feed.
        :param context: the context to get the feed metadata.
        :param path: the path to output.
        :param url: the publicly visible feed URL; if None, path is used
            instead
        :param feed_type: the feed type to use (atom or rss)
        :param override_output: boolean telling if we can override previous
            output with the same name (and if next files written with the same
            name should be skipped to keep that one)
        :param feed_title: the title of the feed.
        """
        ...

    def write_file(
        self,
        name,
        template,
        context,
        relative_urls=...,
        paginated=...,
        template_name=...,
        override_output=...,
        url=...,
        **kwargs,
    ):  # -> None:
        """Render the template and write the file.

        :param name: name of the file to output
        :param template: template to use to generate the content
        :param context: dict to pass to the templates.
        :param relative_urls: use relative urls or absolutes ones
        :param paginated: dict of article list to paginate - must have the
            same length (same list in different orders)
        :param template_name: the template name, for pagination
        :param override_output: boolean telling if we can override previous
            output with the same name (and if next files written with the same
            name should be skipped to keep that one)
        :param url: url of the file (needed by the paginator)
        :param **kwargs: additional variables to pass to the templates
        """
        ...
