name: Post to Mastodon
on:
  check_run:
    types: [completed]

jobs:
  toot:
    # This listens exactly for the check you just found
    if: github.event.check_run.conclusion == 'success' && github.event.check_run.name == 'Cloudflare Pages'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Mastodon
        uses: nhoizey/github-action-feed-to-mastodon@v2
        with:
          feedUrl: "https://lanie.work/feeds/all.atom.xml"
          mastodonInstance: "https://allovertheplace.ca"
          mastodonToken: ${{ secrets.MASTODON_TOKEN }}
